name: example
description: flutter_side_menu example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.21.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_side_menu:
    path: ../
  go_router: ^14.1.4
  badges: ^3.1.2

flutter:
  uses-material-design: true
